-- BankItems frFR Locale File (Credits: pettigrow)
-- THE CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/bank-items/localization/

if GetLocale() ~= "frFR" then return end
local L = BANKITEMS_LOCALIZATION

--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to limit to %d entries"] = "     |cffeda55f Click|r to limit to %d entries"--]] 
--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to show %d additional entries"] = "     |cffeda55f Click|r to show %d additional entries"--]] 
L["-- /bi all : open BankItems and all bags"] = "-- /bi all : ouvre BankItems et tous les sacs"
L["-- /bi allbank : open BankItems and all bank bags only"] = "-- /bi allbank : ouvre BankItems et uniquement tous les sacs de banque"
L["-- /bi charname : open bank of charname on the same server"] = "-- /bi charname : ouvre la banque de charname sur ce serveur."
L["-- /bi clear : clear currently selected player's info"] = "-- /bi clear : efface les infos du personnage actuellement sélectionné"
L["-- /bi clearall : clear all players' info"] = "-- /bi clearall : efface les infos de tous les joueurs"
L["-- /bi hidebutton : hide the minimap button"] = "-- /bi hidebutton : masque le bouton de la minicarte"
L["-- /bi open charname : open bank of charname on the same server"] = "-- /bi open charname : ouvre la banque de charname sur ce serveur."
L["-- /bi search itemname : search for items"] = "-- /bi search nomobjet : recherche l'objet indiqué"
L["-- /bi showbutton : show the minimap button"] = "-- /bi showbutton : affiche le bouton de la minicarte"
L["-- /bigb : open BankItems guild bank"] = "-- /bigb : ouvre la banque de guilde dans BankItems"
L["-- /bigb clear : clear currently selected guild's info"] = "-- /bigb clear : efface les infos de la guilde sélectionnée"
L["-- /bis itemname : search for items"] = "-- /bis nomobjet : recherche l'objet indiqué"
--[[Translation missing --]]
--[[ L["%.0fK"] = "%.0fK"--]] 
--[[Translation missing --]]
--[[ L["%.1fK"] = "%.1fK"--]] 
L["%d guild bank(s) selected"] = "%d banque(s) de guilde cochée(s)"
L["%dg %ds %dc"] = "%do %da %dc"
--[[Translation missing --]]
--[[ L["%s data appears out-of-date."] = "%s data appears out-of-date."--]] 
--[[Translation missing --]]
--[[ L["%s data appears out-of-date. Please visit the %s on this character."] = "%s data appears out-of-date. Please visit the %s on this character."--]] 
L["%s data not found. Please log on this character."] = "Données %s introuvable. Veuillez vous connecter avec ce personnage."
L["%s data not found. Please visit the Auction House on this character."] = "Données %s introuvable. Veuillez vous rendre à l'hotel des ventes avec ce personnage."
--[[Translation missing --]]
--[[ L["%s data not found. Please visit the Bank on this character."] = "%s data not found. Please visit the Bank on this character."--]] 
L["%s data not found. Please visit the Void Storage on this character."] = "Données %s introuvable. Veuillez ouvrir la chambre du vide avec ce personnage."
--[[Translation missing --]]
--[[ L["%s not unlocked on this character."] = "%s not unlocked on this character."--]] 
L["(Not seen before)"] = "(jamais vu auparavant)"
--[[Translation missing --]]
--[[ L["|cffeda55fAlt-Click|r to toggle BankItems %s"] = "|cffeda55fAlt-Click|r to toggle BankItems %s"--]] 
L["|cffeda55fClick|r to toggle BankItems"] = "|cffeda55fClic gauche|r pour afficher/masquer BankItems."
--[[Translation missing --]]
--[[ L["|cffeda55fCtrl-Click|r to toggle BankItems %s"] = "|cffeda55fCtrl-Click|r to toggle BankItems %s"--]] 
--[[Translation missing --]]
--[[ L["|cffeda55fShift-Click|r to toggle BankItems %s"] = "|cffeda55fShift-Click|r to toggle BankItems %s"--]] 
L["<%s>'s guild bank has not purchased any guild bank tabs."] = "La banque de guilde de <%s> n'a aucun onglet."
L["All players' data have been cleared."] = "Les données de tous les personnages ont été effacées."
L["All Realms"] = "Tout serveur"
L["Bag %d Item %d:"] = "Sac %d Objet %d:"
--[[Translation missing --]]
--[[ L["Bag %d:"] = "Bag %d:"--]] 
L["Bags"] = "Sacs"
L["Bank"] = "Banque"
L["Bank Item %d:"] = "Objet de banque %d:"
L["BankItems Bindings"] = "Raccourcis BankItems"
L["BankItems Options"] = "Options de BankItems"
L["BANKITEMS_CAUTION_TEXT"] = [=[ATTENTION : Certains objets n'ont pas été parsed/affichés dans ce rapport car ils n'existent pas pas encore dans votre cache local de WoW. Un patch WoW récent ou une mise à jour du lanceur a sans doute causé le nettoyage du cache local. Connectez ce personnage et ouvrez la banque pour corriger ceci, OU passez votre souris sur tous les objets de tous les sacs pour faire une requête serveur pour chaque lien d'objet (ceci peut vous déconnecter).
]=]
--[[Translation missing --]]
--[[ L["BANKITEMS_CAUTION_TEXT_2"] = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"--]] 
L["Check to show all saved characters, regardless of realm or faction."] = "Cochez pour afficher tous les personnages sauvegardés, quelques soit leur royaume ou leur faction."
L["Check to show characters from the opposite faction (includes BankItems tooltips)."] = "Cochez pour afficher les personnages de la faction adverse (inclus les bulles d'aide de BankItems)."
L["Contents of:"] = "Contenu de:"
--[[Translation missing --]]
--[[ L["Delete a Character:"] = "Delete a Character:"--]] 
--[[Translation missing --]]
--[[ L["Delete a Guild:"] = "Delete a Guild:"--]] 
--[[Translation missing --]]
--[[ L["Delete Data for..."] = "Delete Data for..."--]] 
--[[Translation missing --]]
--[[ L["Entry Limit %d"] = "Entry Limit %d"--]] 
L["Equipped"] = "Équipé"
L["Equipped Items"] = "Objets équipés"
L["Export BankItems..."] = "Exporter BankItems..."
L["Group similar items"] = "Grouper les objets similaires"
L["GuildBank"] = "BanqueGuilde"
L["has"] = "en a"
--[[Translation missing --]]
--[[ L["Hold down|cffeda55f Alt|r to show %d additional entries"] = "Hold down|cffeda55f Alt|r to show %d additional entries"--]] 
L["Ignore unstackable soulbound items"] = "Ignorer les objets liés non empilables"
L["Include the following guild banks:"] = "Inclure les banques de guilde suivantes:"
L["Items in Mailbox"] = "Objets du courrier"
L["Left-click to open BankItems."] = "Clic gauche pour ouvrir BankItems."
L["Lock main window from being moved"] = "Verrouiller la fenêtre principale"
L["Mailbox data not found. Please visit the mailbox on this character."] = "Données de la boîte aux lettres introuvables. Veuillez ouvrir votre boîte aux lettres avec ce personnage."
L["Minimap Button Position %d"] = "Position du bouton de la minicarte %d"
L["Minimap Button Radius %d"] = "Rayon du bouton de la minicarte %d"
L["Money (cumulative)"] = "Argent (cumulé)"
L["Money:"] = "Argent:"
L["No Guild Bank Data"] = "Banques de guilde : aucune donnée"
L["No Guild Bank Tabs"] = "Aucun onglet de guilde"
L["Note - Blizzard frames doesn't like it if your scale isn't 100% when using this option."] = "Note - Les fenêtres de Blizzard n'aiment pas si votre échelle n'est pas de 100% quand vous utilisez cette option."
L["of"] = "de"
L["OfflineBank"] = "BanqueHorsLigne"
L["On the command \"/bi\":"] = "À la commande \"/bi\":"
L["Open auction house bag"] = "Ouvre le sac de l'hotel des ventes"
L["Open bank bags"] = "Ouvrir les sacs de banque"
L["Open BankItems and..."] = "Ouvrir BankItems et..."
L["Open BankItems bags with Blizzard bags"] = "Ouvrir les sacs de BI avec ceux de Blizzard"
L["Open BankItems with Blizzard windows"] = "Ouvrir BankItems avec les fenêtres Blizzard"
L["Open currencies bag"] = "Ouvrir le sac des monnaies"
L["Open equipped items bag"] = "Ouvre le sac de l'équipement"
L["Open inventory bags"] = "Ouvrir les sacs de l'inventaire"
L["Open mail bag"] = "Ouvrir le sac du courrier"
L["Open reagent bank"] = "Ouvre le sac de la banque de composants "
L["Open void storage bag"] = "Ouvre le sac de la chambre du vide"
L["Options..."] = "Options..."
L["Right-click and drag to move this button."] = "Clic droit et saisir pour déplacer ce bouton."
L["Scaling %d%%"] = "Échelle %d%%"
L["Search bank and bank bags"] = "Rechercher dans la banque et dans ses sacs"
L["Search BankItems..."] = "Rechercher dans BankItems..."
L["Search equipped gear"] = "Rechercher dans les objets équipés"
L["Search for \"%s\" complete."] = "Recherche concernant \"%s\" terminée."
--[[Translation missing --]]
--[[ L["Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."] = "Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."--]] 
L["Search guild banks"] = "Rechercher dans la banque de guilde"
L["Search inventory bags"] = "Rechercher dans les sacs de l'inventaire"
L["Search mailbox"] = "Rechercher dans la boîte aux lettres"
L["Search these bags..."] = "Rechercher dans..."
--[[Translation missing --]]
--[[ L["Show All Characters"] = "Show All Characters"--]] 
L["Show All Realms"] = "Tous les royaumes"
L["Show bag prefix"] = "Afficher le préfixe des sacs"
--[[Translation missing --]]
--[[ L["Show character gold in total gold tooltip"] = "Show character gold in total gold tooltip"--]] 
L["Show extra item tooltip information"] = "Infos suppl. dans l'infobulle des objets"
--[[Translation missing --]]
--[[ L["Show only exact item matches in tooltip counts"] = "Show only exact item matches in tooltip counts"--]] 
L["Show Opposite Faction"] = "Afficher faction adverse"
--[[Translation missing --]]
--[[ L["Show reagent bank contents in a bag"] = "Show reagent bank contents in a bag"--]] 
L["Show the minimap button"] = "Afficher le bouton de la minicarte"
--[[Translation missing --]]
--[[ L["Show void storage contents in a bag"] = "Show void storage contents in a bag"--]] 
--[[Translation missing --]]
--[[ L["Sort Ascending"] = "Sort Ascending"--]] 
--[[Translation missing --]]
--[[ L["Sort data broker gold tooltip in ascending order"] = "Sort data broker gold tooltip in ascending order"--]] 
--[[Translation missing --]]
--[[ L["Tab %d"] = "Tab %d"--]] 
L["Tab %d Item %d:"] = "Onglet %d Objet %d:"
L["Toggle BankItems"] = "Ouvrir/fermer BankItems"
L["Toggle BankItems and all Bags"] = "Ouvrir/fermer BankItems et les sacs"
L["Toggle BankItems and all Bank Bags"] = "Ouvrir/fermer BankItems et les sacs de banque"
L["Toggle BankItems Guild Bank"] = "Ouvrir/fermer la banque de guilde de BankItems"
L["Total"] = "Total"
L["Total: %d"] = "Total: %d"
L["Transparency %d%%"] = "Transparence %d%%"
L["Type /bi or /bankitems to open BankItems"] = "Tapez /bi ou /bankitems pour ouvrir BankItems"
L["View bank/inventory/mail contents from anywhere!"] = "Permet de voir le contenu de votre banque/inventaire/courrier de n'importe où !"
L["View Guild Bank contents from anywhere!"] = "Permet de voir le contenu de la banque de guilde de n'importe où !"
L["You do not have any guild bank data to display."] = "Il n'y a aucune donnée concernant les banques de guilde à afficher."
L["You have not seen the contents of \"%s\" before"] = "Vous n'avez encore jamais vu le contenu de l'onglet \"%s\"."

