-- BankItems ruRU Locale File (Credits: StingerSoft)
-- THE CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/bank-items/localization/

if GetLocale() ~= "ruRU" then return end
local L = BANKITEMS_LOCALIZATION

--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to limit to %d entries"] = "     |cffeda55f Click|r to limit to %d entries"--]] 
--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to show %d additional entries"] = "     |cffeda55f Click|r to show %d additional entries"--]] 
L["-- /bi all : open BankItems and all bags"] = "-- /bi all : открыть BankItems и все сумки"
L["-- /bi allbank : open BankItems and all bank bags only"] = "-- /bi allbank : открыть BankItems и все сумки банка"
L["-- /bi charname : open bank of charname on the same server"] = "-- /bi charname : открыть банк персонажа на этом сервере"
L["-- /bi clear : clear currently selected player's info"] = "-- /bi clear : очистить информацию о выбранном игроке"
L["-- /bi clearall : clear all players' info"] = "-- /bi clearall : очистить информацию о всех игроках"
L["-- /bi hidebutton : hide the minimap button"] = "-- /bi hidebutton : скрыть кнопку у мини-карты"
L["-- /bi open charname : open bank of charname on the same server"] = "-- /bi open charname : открыть банк персонажа на этом сервере"
L["-- /bi search itemname : search for items"] = "-- /bi search itemname : поиск предметов"
L["-- /bi showbutton : show the minimap button"] = "-- /bi showbutton : показать кнопку у мини-карты"
L["-- /bigb : open BankItems guild bank"] = "-- /bigb : открыть гильдейский банк BankItems"
L["-- /bigb clear : clear currently selected guild's info"] = "-- /bigb clear : очистить информацию о выбранной гильдии"
L["-- /bis itemname : search for items"] = "-- /bis itemname : поиск предметов"
--[[Translation missing --]]
--[[ L["%.0fK"] = "%.0fK"--]] 
--[[Translation missing --]]
--[[ L["%.1fK"] = "%.1fK"--]] 
L["%d guild bank(s) selected"] = "%d гильд. банк(а) выбран(о)"
L["%dg %ds %dc"] = "%dз %dс %dм"
--[[Translation missing --]]
--[[ L["%s data appears out-of-date."] = "%s data appears out-of-date."--]] 
--[[Translation missing --]]
--[[ L["%s data appears out-of-date. Please visit the %s on this character."] = "%s data appears out-of-date. Please visit the %s on this character."--]] 
L["%s data not found. Please log on this character."] = "Нет информации: %s. Зайдите в игру этим персонажем."
L["%s data not found. Please visit the Auction House on this character."] = "Нет информации: %s. Посетите аукцион этим персонажем."
--[[Translation missing --]]
--[[ L["%s data not found. Please visit the Bank on this character."] = "%s data not found. Please visit the Bank on this character."--]] 
L["%s data not found. Please visit the Void Storage on this character."] = "Нет информации: %s. Откройте Хранилище Бездны этим персонажем."
--[[Translation missing --]]
--[[ L["%s not unlocked on this character."] = "%s not unlocked on this character."--]] 
L["(Not seen before)"] = "(Не осмотрено)"
L["|cffeda55fAlt-Click|r to toggle BankItems %s"] = "|cffeda55fAlt++щелчок|r для переключения BankItems %s"
L["|cffeda55fClick|r to toggle BankItems"] = "|cffeda55fКлик|r открывает/закрывает окно BankItems"
L["|cffeda55fCtrl-Click|r to toggle BankItems %s"] = "|cffeda55fCtrl+щелчок|r для переключения BankItems %s"
L["|cffeda55fShift-Click|r to toggle BankItems %s"] = "|cffeda55fShift+щелчок|r для переключения BankItems %s"
L["<%s>'s guild bank has not purchased any guild bank tabs."] = "В гильдейском банке <%s> не приобретено ни одного сейфа."
L["All players' data have been cleared."] = "Данные о всех персонажах были очищены."
L["All Realms"] = "Все миры"
L["Bag %d Item %d:"] = "Сумка %d предмет %d:"
--[[Translation missing --]]
--[[ L["Bag %d:"] = "Bag %d:"--]] 
L["Bags"] = "В сумках"
L["Bank"] = "В банке"
L["Bank Item %d:"] = "Предмет в банке %d:"
L["BankItems Bindings"] = "Клавиши BankItems"
L["BankItems Options"] = "Настройки BankItems"
L["BANKITEMS_CAUTION_TEXT"] = [=[ВНИМАНИЕ: Некоторые предметы не были проанализированы / не отобразились в настоящем отчете, поскольку они не существуют в вашем локальном кэше WoW. Недавнее обновление WoW или меню запуска вызвало очищение локального кэша. Войдите за данного персонажа и посетите банк для исправления данного положения, или наведите курсор мыши на каждый предмет в каждой сумке для запроса информации с сервера (это может вызвать разрыв соединения с сервером).
]=]
--[[Translation missing --]]
--[[ L["BANKITEMS_CAUTION_TEXT_2"] = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"--]] 
L["Check to show all saved characters, regardless of realm or faction."] = "Просмотр всех сохранённых персонажей, независимо от сервера или фракции."
L["Check to show characters from the opposite faction (includes BankItems tooltips)."] = "Просмотр персонажей обоих фракций (добавляет информацию в подсказки BankItems)."
L["Contents of:"] = "Содержимое:"
--[[Translation missing --]]
--[[ L["Delete a Character:"] = "Delete a Character:"--]] 
--[[Translation missing --]]
--[[ L["Delete a Guild:"] = "Delete a Guild:"--]] 
--[[Translation missing --]]
--[[ L["Delete Data for..."] = "Delete Data for..."--]] 
--[[Translation missing --]]
--[[ L["Entry Limit %d"] = "Entry Limit %d"--]] 
L["Equipped"] = "Экипировка"
L["Equipped Items"] = "Экипировка"
L["Export BankItems..."] = "Экспорт..."
L["Group similar items"] = "Подобные предметы"
L["GuildBank"] = "Гильдейский банк"
L["has"] = "имеет"
--[[Translation missing --]]
--[[ L["Hold down|cffeda55f Alt|r to show %d additional entries"] = "Hold down|cffeda55f Alt|r to show %d additional entries"--]] 
L["Ignore unstackable soulbound items"] = "Игнорировать именные не объединяющиеся предметы"
L["Include the following guild banks:"] = "Включая следующие гильдейские банки:"
L["Items in Mailbox"] = "Почтовый ящик"
L["Left-click to open BankItems."] = "[Левый-клик] открывает/закрывает окно BankItems."
L["Lock main window from being moved"] = "Зафиксировать главное окно от перемещения"
L["Mailbox data not found. Please visit the mailbox on this character."] = "Нет информации о содержимом почтового ящика. Откройте почтовый ящик этим персонажем."
L["Minimap Button Position %d"] = "Позиция кнопки у мини-карты %d"
L["Minimap Button Radius %d"] = "Радиус кнопки у мини-карты %d"
L["Money (cumulative)"] = "Деньги (всего)"
L["Money:"] = "Деньги:"
L["No Guild Bank Data"] = "Нет данных о гильдейском банке"
L["No Guild Bank Tabs"] = "Нет сейфов гильдейского банка"
L["Note - Blizzard frames doesn't like it if your scale isn't 100% when using this option."] = "Заметка - Открытие окна банка Blizzard при использовании данной опции не рекомендуется, если не установлен масштаб 100%."
L["of"] = "-"
L["OfflineBank"] = "Автономный банк"
L["On the command \"/bi\":"] = "По команде \"/bi\":"
L["Open auction house bag"] = "Аукцион"
L["Open bank bags"] = "Сумки банка"
L["Open BankItems and..."] = "Открыть BankItems и..."
L["Open BankItems bags with Blizzard bags"] = "Открывать сумки BankItems рядом с сумками персонажа"
L["Open BankItems with Blizzard windows"] = "Открыть BankItems рядом со стандартными окнами"
L["Open currencies bag"] = "Сумку валюты"
L["Open equipped items bag"] = "Сумку экипировки"
L["Open inventory bags"] = "Сумки инвентаря"
L["Open mail bag"] = "Почтовую сумку"
L["Open reagent bank"] = "Банк реагентов"
L["Open void storage bag"] = "Хранилище Бездны"
L["Options..."] = "Настройки..."
L["Right-click and drag to move this button."] = "[Правый-клик + тянуть] перемещает эту кнопку."
L["Scaling %d%%"] = "Масштаб %d%%"
L["Search bank and bank bags"] = "Поиск в банке и сумках банка"
L["Search BankItems..."] = "Поиск..."
L["Search equipped gear"] = "Поиск в экипировке"
L["Search for \"%s\" complete."] = "Поиск \"%s\" закончен."
--[[Translation missing --]]
--[[ L["Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."] = "Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."--]] 
L["Search guild banks"] = "Поиск в гильдейских банках"
L["Search inventory bags"] = "Поиск в сумках инвентаря"
L["Search mailbox"] = "Поиск в почтовом ящике"
L["Search these bags..."] = "Поиск в сумках..."
--[[Translation missing --]]
--[[ L["Show All Characters"] = "Show All Characters"--]] 
L["Show All Realms"] = "Все сервера"
L["Show bag prefix"] = "Показать префикс сумки"
--[[Translation missing --]]
--[[ L["Show character gold in total gold tooltip"] = "Show character gold in total gold tooltip"--]] 
L["Show extra item tooltip information"] = "Показать дополнительную информацию в подсказке предмета"
--[[Translation missing --]]
--[[ L["Show only exact item matches in tooltip counts"] = "Show only exact item matches in tooltip counts"--]] 
L["Show Opposite Faction"] = "Обе фракции"
L["Show reagent bank contents in a bag"] = "Показывать в сумке содержимое банка реагентов"
L["Show the minimap button"] = "Показать кнопку у мини-карты"
L["Show void storage contents in a bag"] = "Показывать в сумке содержимое Хранилища Бездны"
--[[Translation missing --]]
--[[ L["Sort Ascending"] = "Sort Ascending"--]] 
--[[Translation missing --]]
--[[ L["Sort data broker gold tooltip in ascending order"] = "Sort data broker gold tooltip in ascending order"--]] 
--[[Translation missing --]]
--[[ L["Tab %d"] = "Tab %d"--]] 
L["Tab %d Item %d:"] = "Раздел %d предмет %d:"
L["Toggle BankItems"] = "Открыть/Закрыть BankItems"
L["Toggle BankItems and all Bags"] = "Открыть/Закрыть BankItems и все сумки"
L["Toggle BankItems and all Bank Bags"] = "Открыть/Закрыть BankItems и все сумки банка"
L["Toggle BankItems Guild Bank"] = "Открыть/Закрыть гильдейский банк BankItems"
L["Total"] = "Всего"
L["Total: %d"] = "Всего: %d"
L["Transparency %d%%"] = "Прозрачность %d%%"
L["Type /bi or /bankitems to open BankItems"] = "Для открытия BankItems введите: /bi или /bankitems"
L["View bank/inventory/mail contents from anywhere!"] = "Просмотр содержимого банка/инвентаря/почты в любое время!"
L["View Guild Bank contents from anywhere!"] = "Просмотр содержимого гильдейского банка в любой момент!"
L["You do not have any guild bank data to display."] = "У вас нет никаких данных о гильдейском банке для отображения."
L["You have not seen the contents of \"%s\" before"] = "Вы раньше не осматривали содержимое \"%s\""

