-- BankItems zhCN Locale File (Credits: Isler)
-- THE CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/bank-items/localization/

if GetLocale() ~= "zhCN" then return end
local L = BANKITEMS_LOCALIZATION

--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to limit to %d entries"] = "     |cffeda55f Click|r to limit to %d entries"--]] 
--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to show %d additional entries"] = "     |cffeda55f Click|r to show %d additional entries"--]] 
L["-- /bi all : open BankItems and all bags"] = "-- /bi all : 打开离线银行及所有包裹"
L["-- /bi allbank : open BankItems and all bank bags only"] = "-- /bi allbank : 打开离线银行及所有银行包裹"
L["-- /bi charname : open bank of charname on the same server"] = "-- /bi charname : 打开本服务器指定人物的离线银行"
L["-- /bi clear : clear currently selected player's info"] = "-- /bi clear : 清除所选择的人物的信息"
L["-- /bi clearall : clear all players' info"] = "-- /bi clearall : 清除所有人物的信息"
L["-- /bi hidebutton : hide the minimap button"] = "-- /bi hidebutton : 隐藏小地图按钮"
L["-- /bi open charname : open bank of charname on the same server"] = "-- /bi open charname : 打开本服务器指定人物的离线银行"
L["-- /bi search itemname : search for items"] = "-- /bi search itemname : 搜索物品"
L["-- /bi showbutton : show the minimap button"] = "-- /bi showbutton : 显示小地图按钮"
L["-- /bigb : open BankItems guild bank"] = "-- /bigb: 打开离线公会银行"
L["-- /bigb clear : clear currently selected guild's info"] = "-- /bigb clear : 清除所选择的公会银行信息"
L["-- /bis itemname : search for items"] = "-- /bis itemname : 搜索物品"
--[[Translation missing --]]
--[[ L["%.0fK"] = "%.0fK"--]] 
--[[Translation missing --]]
--[[ L["%.1fK"] = "%.1fK"--]] 
L["%d guild bank(s) selected"] = "已选择 %d 个公会银行"
L["%dg %ds %dc"] = "%d金 %d银 %d铜"
--[[Translation missing --]]
--[[ L["%s data appears out-of-date."] = "%s data appears out-of-date."--]] 
--[[Translation missing --]]
--[[ L["%s data appears out-of-date. Please visit the %s on this character."] = "%s data appears out-of-date. Please visit the %s on this character."--]] 
L["%s data not found. Please log on this character."] = "没有%s的资料，请登录该人物。"
L["%s data not found. Please visit the Auction House on this character."] = "没有%s的资料，请登录该人物后访问拍卖行。"
--[[Translation missing --]]
--[[ L["%s data not found. Please visit the Bank on this character."] = "%s data not found. Please visit the Bank on this character."--]] 
L["%s data not found. Please visit the Void Storage on this character."] = "没有%s的资料，请登录该人物后访问虚空仓库。"
--[[Translation missing --]]
--[[ L["%s not unlocked on this character."] = "%s not unlocked on this character."--]] 
L["(Not seen before)"] = "（从未查看过）"
L["|cffeda55fAlt-Click|r to toggle BankItems %s"] = "|cffeda55fAlt-左键|r切换BankItems %s"
L["|cffeda55fClick|r to toggle BankItems"] = "|cffeda55f左键点击|r打开离线银行"
L["|cffeda55fCtrl-Click|r to toggle BankItems %s"] = "|cffeda55fCtrl-左键|r切换BankItems %s"
L["|cffeda55fShift-Click|r to toggle BankItems %s"] = "|cffeda55fShift-左键|r切换BankItems %s"
L["<%s>'s guild bank has not purchased any guild bank tabs."] = "<%s> 的公会银行还没有购买任何标签。"
L["All players' data have been cleared."] = "所有人物的数据已经清除。"
L["All Realms"] = "所有服务器"
L["Bag %d Item %d:"] = "包裹 %d 物品 %d："
--[[Translation missing --]]
--[[ L["Bag %d:"] = "Bag %d:"--]] 
L["Bags"] = "包裹"
L["Bank"] = "银行"
L["Bank Item %d:"] = "银行物品 %d："
L["BankItems Bindings"] = "离线银行"
L["BankItems Options"] = "离线银行设置"
L["BANKITEMS_CAUTION_TEXT"] = [=[注意：一些装备未在报告中解析并发布因为它们没有在本地缓存中被发现。最近的一次游戏更新清空了本地缓存。你可以登陆该角色并浏览银行物品来解决这个问题或者把鼠标在每个包裹的每件物品上悬停来向服务器查询物品链接（这可能导致你掉线）。
]=]
--[[Translation missing --]]
--[[ L["BANKITEMS_CAUTION_TEXT_2"] = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"--]] 
L["Check to show all saved characters, regardless of realm or faction."] = "点击这里选择所有保存的人物的银行信息（所有服务器）。"
L["Check to show characters from the opposite faction (includes BankItems tooltips)."] = "勾选此项显示敌对阵营角色（包括BankItems说明提示）。"
L["Contents of:"] = "搜索结果："
--[[Translation missing --]]
--[[ L["Delete a Character:"] = "Delete a Character:"--]] 
--[[Translation missing --]]
--[[ L["Delete a Guild:"] = "Delete a Guild:"--]] 
--[[Translation missing --]]
--[[ L["Delete Data for..."] = "Delete Data for..."--]] 
--[[Translation missing --]]
--[[ L["Entry Limit %d"] = "Entry Limit %d"--]] 
L["Equipped"] = "装备"
L["Equipped Items"] = "装备的物品"
L["Export BankItems..."] = "输出离线银行..."
L["Group similar items"] = "分组相似物品"
L["GuildBank"] = "公会银行"
L["has"] = "拥有"
--[[Translation missing --]]
--[[ L["Hold down|cffeda55f Alt|r to show %d additional entries"] = "Hold down|cffeda55f Alt|r to show %d additional entries"--]] 
L["Ignore unstackable soulbound items"] = "忽略不可堆叠的灵魂绑定物品"
L["Include the following guild banks:"] = "包含以下公会银行："
L["Items in Mailbox"] = "邮件内的物品"
L["Left-click to open BankItems."] = "左键点击打开离线银行。"
L["Lock main window from being moved"] = "锁定主窗口以防止拖动"
L["Mailbox data not found. Please visit the mailbox on this character."] = "没有邮箱资料，请登录该人物后访问邮箱。"
L["Minimap Button Position %d"] = "小地图按钮位置 %d"
L["Minimap Button Radius %d"] = "小地图按钮半径 %d"
L["Money (cumulative)"] = "金钱（总计）"
L["Money:"] = "金钱："
L["No Guild Bank Data"] = "没有公会银行数据"
L["No Guild Bank Tabs"] = "没有公会银行标签"
L["Note - Blizzard frames doesn't like it if your scale isn't 100% when using this option."] = "注意 - 当你使用这个选项，且缩放不是100%的时候，可能会出现不兼容的情况。"
L["of"] = "在"
L["OfflineBank"] = "离线银行"
L["On the command \"/bi\":"] = "在输入命令 \"/bi\":"
L["Open auction house bag"] = "打开拍卖行背包"
L["Open bank bags"] = "打开银行包裹"
L["Open BankItems and..."] = "打开离线银行的同时..."
L["Open BankItems bags with Blizzard bags"] = "以暴雪的包裹方式打开离线银行的包裹"
L["Open BankItems with Blizzard windows"] = "以暴雪的窗口方式打开离线银行"
L["Open currencies bag"] = "打开货币标签页"
L["Open equipped items bag"] = "打开装备包裹"
L["Open inventory bags"] = "打开随身包裹"
L["Open mail bag"] = "打开邮件包裹"
L["Open reagent bank"] = "打开材料银行"
L["Open void storage bag"] = "打开虚空仓库背包"
L["Options..."] = "设置..."
L["Right-click and drag to move this button."] = "右键点击并拖动来移动按钮。"
L["Scaling %d%%"] = "缩放 %d%%"
L["Search bank and bank bags"] = "搜索银行包裹"
L["Search BankItems..."] = "搜索离线银行..."
L["Search equipped gear"] = "搜索装备包裹"
L["Search for \"%s\" complete."] = "搜索 \"%s\" 完成。"
--[[Translation missing --]]
--[[ L["Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."] = "Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."--]] 
L["Search guild banks"] = "搜索公会银行包裹"
L["Search inventory bags"] = "搜索随身包裹"
L["Search mailbox"] = "搜索邮件包裹"
L["Search these bags..."] = "搜索这些包裹..."
--[[Translation missing --]]
--[[ L["Show All Characters"] = "Show All Characters"--]] 
L["Show All Realms"] = "显示所有服务器"
L["Show bag prefix"] = "显示包裹前缀"
--[[Translation missing --]]
--[[ L["Show character gold in total gold tooltip"] = "Show character gold in total gold tooltip"--]] 
L["Show extra item tooltip information"] = "在物品上显示额外的鼠标提示信息"
--[[Translation missing --]]
--[[ L["Show only exact item matches in tooltip counts"] = "Show only exact item matches in tooltip counts"--]] 
L["Show Opposite Faction"] = "显示敌对阵营"
L["Show reagent bank contents in a bag"] = "显示材料银行物品"
L["Show the minimap button"] = "显示小地图按钮"
L["Show void storage contents in a bag"] = "显示虚空仓库物品"
--[[Translation missing --]]
--[[ L["Sort Ascending"] = "Sort Ascending"--]] 
--[[Translation missing --]]
--[[ L["Sort data broker gold tooltip in ascending order"] = "Sort data broker gold tooltip in ascending order"--]] 
--[[Translation missing --]]
--[[ L["Tab %d"] = "Tab %d"--]] 
L["Tab %d Item %d:"] = "标签 %d 物品 %d："
L["Toggle BankItems"] = "打开离线银行"
L["Toggle BankItems and all Bags"] = "打开离线银行及所有包裹"
L["Toggle BankItems and all Bank Bags"] = "打开离线银行及银行包裹"
L["Toggle BankItems Guild Bank"] = "打开离线公会银行"
L["Total"] = "总计"
L["Total: %d"] = "总计：%d"
L["Transparency %d%%"] = "透明度 %d%%"
L["Type /bi or /bankitems to open BankItems"] = "输入 /bi 或 /bankitems 打开离线银行"
L["View bank/inventory/mail contents from anywhere!"] = "让你可以随时浏览本ID所有服务器所有人物的装备以及背包、邮件和银行中的物品"
L["View Guild Bank contents from anywhere!"] = "让你可以随时浏览本角色所在公会的公会银行中的物品"
L["You do not have any guild bank data to display."] = "没有任何可供显示的公会银行数据。"
L["You have not seen the contents of \"%s\" before"] = "你以前从未看过 \"%s\" 的内容"

