-- BankItems koKR Locale File
-- THE CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/bank-items/localization/

if GetLocale() ~= "koKR" then return end
local L = BANKITEMS_LOCALIZATION

--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to limit to %d entries"] = "     |cffeda55f Click|r to limit to %d entries"--]] 
--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to show %d additional entries"] = "     |cffeda55f Click|r to show %d additional entries"--]] 
L["-- /bi all : open BankItems and all bags"] = "-- /bi all : BankItems과 모든 가방 열기"
L["-- /bi allbank : open BankItems and all bank bags only"] = "-- /bi allbank : BankItems과 모든 은행 가방만 열기"
L["-- /bi charname : open bank of charname on the same server"] = "-- /bi 캐릭터명 : 동일한 서버에 있는 캐릭터의 은행 열기"
L["-- /bi clear : clear currently selected player's info"] = "-- /bi clear : 현재 선택된 플레이어의 정보 지우기"
L["-- /bi clearall : clear all players' info"] = "-- /bi clearall : 모든 플레이어의 정보 지우기"
L["-- /bi hidebutton : hide the minimap button"] = "-- /bi hidebutton : 미니맵 버튼 숨김"
L["-- /bi open charname : open bank of charname on the same server"] = "-- /bi open 캐릭터명 : 동일한 서버에 있는 캐릭터의 은행 열기"
L["-- /bi search itemname : search for items"] = "-- /bi search itemname : 아이템 검색"
L["-- /bi showbutton : show the minimap button"] = "-- /bi showbutton : 미니맵 버튼 보기"
L["-- /bigb : open BankItems guild bank"] = "-- /bigb: BankItems 길드 금고 열기"
L["-- /bigb clear : clear currently selected guild's info"] = "-- /bigb clear : 현재 선택된 길드 정보 삭제"
L["-- /bis itemname : search for items"] = "-- /bis itemname : 아이템 검색"
--[[Translation missing --]]
--[[ L["%.0fK"] = "%.0fK"--]] 
--[[Translation missing --]]
--[[ L["%.1fK"] = "%.1fK"--]] 
L["%d guild bank(s) selected"] = "길드 금고 %d 선택됨"
L["%dg %ds %dc"] = "%dg %ds %dc"
--[[Translation missing --]]
--[[ L["%s data appears out-of-date."] = "%s data appears out-of-date."--]] 
--[[Translation missing --]]
--[[ L["%s data appears out-of-date. Please visit the %s on this character."] = "%s data appears out-of-date. Please visit the %s on this character."--]] 
L["%s data not found. Please log on this character."] = "%s 데이터를 찾을 수 없습니다. 이 캐릭터로 접속하세요."
L["%s data not found. Please visit the Auction House on this character."] = "%s 데이터를 찾을 수 없습니다. 이 캐릭터로 경매장을 방문하세요."
--[[Translation missing --]]
--[[ L["%s data not found. Please visit the Bank on this character."] = "%s data not found. Please visit the Bank on this character."--]] 
L["%s data not found. Please visit the Void Storage on this character."] = "%s 데이터를 찾을 수 없습니다. 이 캐릭터로 공허 보관소를 방문하세요."
--[[Translation missing --]]
--[[ L["%s not unlocked on this character."] = "%s not unlocked on this character."--]] 
L["(Not seen before)"] = "(이전에 본적이 없음)"
L["|cffeda55fAlt-Click|r to toggle BankItems %s"] = "|cffeda55fAlt-Click|r : %s 표시/닫기"
L["|cffeda55fClick|r to toggle BankItems"] = "|cffeda55f클릭|r BankItems 표시/닫기"
L["|cffeda55fCtrl-Click|r to toggle BankItems %s"] = "|cffeda55fCtrl-Click|r : %s 표시/닫기"
L["|cffeda55fShift-Click|r to toggle BankItems %s"] = "|cffeda55fShift-Click|r : %s 표시/닫기"
L["<%s>'s guild bank has not purchased any guild bank tabs."] = "<%s> 길드 금고는 어떤 금고 가방(탭)도 구매하지 않았습니다."
L["All players' data have been cleared."] = "모든 플레이어의 자료가 지워졌습니다."
L["All Realms"] = "모든 서버"
L["Bag %d Item %d:"] = "가방 %d의 아이템 %d:"
--[[Translation missing --]]
--[[ L["Bag %d:"] = "Bag %d:"--]] 
L["Bags"] = "가방"
L["Bank"] = "은행"
L["Bank Item %d:"] = "은행 아이템 %d:"
L["BankItems Bindings"] = "BankItems 단축키"
L["BankItems Options"] = "BankItems 옵션"
L["BANKITEMS_CAUTION_TEXT"] = [=[위험: 몇개의 아이템은 아직 WoW 캐쉬에 없기 때문에 이 보고서에는 분석/표시되지 않았습니다. 최근의 WoW 패치 혹은 정리에 의해 업데이트된 까닭에 지역 캐쉬가 지워진 듯 합니다. 이 문제를 수정하기 위해서 이 캐릭터로 접속해 은행을 방문하거나 각각의 아이템 링크를 서버에 묻기 위해서 모든 가방안의 모든 아이템에 마우스를 올려 놓으십시요(이 작업으로 접속 종료될 수 있습니다).
]=]
--[[Translation missing --]]
--[[ L["BANKITEMS_CAUTION_TEXT_2"] = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"--]] 
L["Check to show all saved characters, regardless of realm or faction."] = "서버 또는 진영에 상관없이 저장된 모든 캐릭터를 보려면 선택하세요."
L["Check to show characters from the opposite faction (includes BankItems tooltips)."] = "선택 시 적대적 세력의 캐릭터를 표시합니다 (Bankitems 툴팁 포함)."
L["Contents of:"] = "내용물:"
--[[Translation missing --]]
--[[ L["Delete a Character:"] = "Delete a Character:"--]] 
--[[Translation missing --]]
--[[ L["Delete a Guild:"] = "Delete a Guild:"--]] 
--[[Translation missing --]]
--[[ L["Delete Data for..."] = "Delete Data for..."--]] 
--[[Translation missing --]]
--[[ L["Entry Limit %d"] = "Entry Limit %d"--]] 
L["Equipped"] = "착용"
L["Equipped Items"] = "착용 아이템"
L["Export BankItems..."] = "BankItems 출력..."
L["Group similar items"] = "유사한 아이템 그룹화"
L["GuildBank"] = "길드 금고"
L["has"] = "소유"
--[[Translation missing --]]
--[[ L["Hold down|cffeda55f Alt|r to show %d additional entries"] = "Hold down|cffeda55f Alt|r to show %d additional entries"--]] 
L["Ignore unstackable soulbound items"] = "중첩할 수 없는 귀속 아이템 무시"
L["Include the following guild banks:"] = "길드 금고를 불러오는 중"
L["Items in Mailbox"] = "우편함의 아이템"
L["Left-click to open BankItems."] = "좌-클릭: BankItems 열기"
L["Lock main window from being moved"] = "이동 상태에서 메인창 잠금"
L["Mailbox data not found. Please visit the mailbox on this character."] = "우편함 데이터를 찾을 수 없습니다. 이 캐릭터로 우편함을 확인하세요."
L["Minimap Button Position %d"] = "미니맵 버튼 위치 %d"
L["Minimap Button Radius %d"] = "미니맵 버튼 반경 %d"
L["Money (cumulative)"] = "소지금 (누적분)"
L["Money:"] = "소지금:"
L["No Guild Bank Data"] = "길드 금고 자료가 없음"
L["No Guild Bank Tabs"] = "길드 금고 가방(탭)이 없음"
L["Note - Blizzard frames doesn't like it if your scale isn't 100% when using this option."] = "주의 - 이 옵션을 사용하는 경우에 만일 그 크기가 100%가 아니라면 블리자드 프레임처럼 기능하지 않습니다."
L["of"] = "-"
L["OfflineBank"] = "오프라인 은행"
L["On the command \"/bi\":"] = "명령어 \"/bi\"로:"
L["Open auction house bag"] = "경매 가방 열기"
L["Open bank bags"] = "은행 가방 열기"
L["Open BankItems and..."] = "BankItems 열기 및..."
L["Open BankItems bags with Blizzard bags"] = "블리자드 가방과 함께 BankItems 가방 열기"
L["Open BankItems with Blizzard windows"] = "블리자드 창과 함께 BankItems 열기"
L["Open currencies bag"] = "화폐 가방 열기"
L["Open equipped items bag"] = "착용 가방 열기"
L["Open inventory bags"] = "소지품 가방 열기"
L["Open mail bag"] = "우편 가방 열기"
L["Open reagent bank"] = "재료 은행 열기"
L["Open void storage bag"] = "공허 보관소 열기"
L["Options..."] = "옵션..."
L["Right-click and drag to move this button."] = "우-클릭 드래그: 이 버튼의 이동"
L["Scaling %d%%"] = "크기 조절 %d%%"
L["Search bank and bank bags"] = "은행과 은행 가방 검색"
L["Search BankItems..."] = "BankItems 검색..."
L["Search equipped gear"] = "착용 장비 검색"
L["Search for \"%s\" complete."] = "\"%s\"의 검색 완료."
--[[Translation missing --]]
--[[ L["Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."] = "Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."--]] 
L["Search guild banks"] = "길드 금고 검색"
L["Search inventory bags"] = "소지품 가방 검색"
L["Search mailbox"] = "우편함 검색"
L["Search these bags..."] = "이 가방을 검색..."
--[[Translation missing --]]
--[[ L["Show All Characters"] = "Show All Characters"--]] 
L["Show All Realms"] = "모든 서버 보기"
L["Show bag prefix"] = "가방 접두사 보기"
--[[Translation missing --]]
--[[ L["Show character gold in total gold tooltip"] = "Show character gold in total gold tooltip"--]] 
L["Show extra item tooltip information"] = "별도의 아이템 툴팁 정보(소유 위치) 보기"
--[[Translation missing --]]
--[[ L["Show only exact item matches in tooltip counts"] = "Show only exact item matches in tooltip counts"--]] 
L["Show Opposite Faction"] = "적대적 세력 표시"
L["Show reagent bank contents in a bag"] = "재료 은행 내용을 가방으로 보기"
L["Show the minimap button"] = "미니맵 버튼 보기"
L["Show void storage contents in a bag"] = "공허 보관소 내용을 가방으로 보기"
--[[Translation missing --]]
--[[ L["Sort Ascending"] = "Sort Ascending"--]] 
--[[Translation missing --]]
--[[ L["Sort data broker gold tooltip in ascending order"] = "Sort data broker gold tooltip in ascending order"--]] 
--[[Translation missing --]]
--[[ L["Tab %d"] = "Tab %d"--]] 
L["Tab %d Item %d:"] = "탭 %d의 아이템 %d:"
L["Toggle BankItems"] = "BankItems 표시"
L["Toggle BankItems and all Bags"] = "BankItems과 모든 가방 표시"
L["Toggle BankItems and all Bank Bags"] = "BankItems과 모든 은행 가방 표시"
L["Toggle BankItems Guild Bank"] = "BankItems 길드 금고 표시"
L["Total"] = "총"
L["Total: %d"] = "총: %d"
L["Transparency %d%%"] = "투명도 %d%%"
L["Type /bi or /bankitems to open BankItems"] = "BankItems 열기는 /bi 혹은 /bankitems를 입력하세요."
L["View bank/inventory/mail contents from anywhere!"] = "어느 곳에서도 은행/소지품/우편의 내용물을 보여줍니다!"
L["View Guild Bank contents from anywhere!"] = "어느 곳에서도 길드 금고의 내용물을 보여줍니다!"
L["You do not have any guild bank data to display."] = "당신은 길드 금고 자료를 볼 수 없습니다."
L["You have not seen the contents of \"%s\" before"] = "당신은 이전에 \"%s\" 금고 내용을 보지 않았습니다"

