-- BankItems itIT Locale File
-- THE CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/bank-items/localization/

if GetLocale() ~= "itIT" then return end
local L = BANKITEMS_LOCALIZATION

--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to limit to %d entries"] = "     |cffeda55f Click|r to limit to %d entries"--]] 
--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to show %d additional entries"] = "     |cffeda55f Click|r to show %d additional entries"--]] 
L["-- /bi all : open BankItems and all bags"] = "-- /bi all : apre BankItems e tutte le Borse"
L["-- /bi allbank : open BankItems and all bank bags only"] = "-- /bi allbank : apre BankItems e solo le Borse della Banca"
L["-- /bi charname : open bank of charname on the same server"] = "-- /bi \"nome personaggio\" : apre la Banca del \"personaggio\" nello stesso server"
L["-- /bi clear : clear currently selected player's info"] = "-- /bi clear : pulisce le informazioni del personaggio attualmente selezionato"
L["-- /bi clearall : clear all players' info"] = "-- /bi clearall : pulisce tutte le informazioni dei personaggi"
L["-- /bi hidebutton : hide the minimap button"] = "-- /bi hidebutton : nasconde il pulsante nella minimappa"
L["-- /bi open charname : open bank of charname on the same server"] = "-- /bi open \"nome personaggio\" : apre la Banca del \"personaggio\" nello stesso server"
L["-- /bi search itemname : search for items"] = "-- /bi search \"nome oggetto\" : ricerca oggetti"
L["-- /bi showbutton : show the minimap button"] = "-- /bi showbutton : mostra il pulsante nella minimappa"
L["-- /bigb : open BankItems guild bank"] = "-- /bigb : apre BankItems nella Banca di Gilda"
L["-- /bigb clear : clear currently selected guild's info"] = "-- /bigb clear : pulisce le informazioni della Gilda attualmente selezionata"
L["-- /bis itemname : search for items"] = "-- /bis \"nome oggetto\" : ricerca oggetti"
--[[Translation missing --]]
--[[ L["%.0fK"] = "%.0fK"--]] 
--[[Translation missing --]]
--[[ L["%.1fK"] = "%.1fK"--]] 
L["%d guild bank(s) selected"] = "Banca %d selezionata"
L["%dg %ds %dc"] = "%do %da %dr"
--[[Translation missing --]]
--[[ L["%s data appears out-of-date."] = "%s data appears out-of-date."--]] 
--[[Translation missing --]]
--[[ L["%s data appears out-of-date. Please visit the %s on this character."] = "%s data appears out-of-date. Please visit the %s on this character."--]] 
L["%s data not found. Please log on this character."] = "Dati per %s non trovati. Per favore, accedi con questo personaggio."
L["%s data not found. Please visit the Auction House on this character."] = "Dati per %s non trovati. Per favore, visita l'Asta con questo personaggio"
--[[Translation missing --]]
--[[ L["%s data not found. Please visit the Bank on this character."] = "%s data not found. Please visit the Bank on this character."--]] 
L["%s data not found. Please visit the Void Storage on this character."] = "Dati per %s non trovati. Per favore, visita la Banca Eterea con questo personaggio."
--[[Translation missing --]]
--[[ L["%s not unlocked on this character."] = "%s not unlocked on this character."--]] 
L["(Not seen before)"] = "(Mai visto prima)"
L["|cffeda55fAlt-Click|r to toggle BankItems %s"] = "|cffeda55fAlt-Click|r per scambiare BankItems %s"
L["|cffeda55fClick|r to toggle BankItems"] = "|cffeda55fClick|r per scambiare BankItems"
L["|cffeda55fCtrl-Click|r to toggle BankItems %s"] = "|cffeda55fCtrl-Click|r per scambiare BankItems %s"
L["|cffeda55fShift-Click|r to toggle BankItems %s"] = "|cffeda55fShift-Click|r per scambiare BankItems %s"
L["<%s>'s guild bank has not purchased any guild bank tabs."] = "La Banca di Gilda di %s non ha nessun scomparto acquistato."
L["All players' data have been cleared."] = "Tutti i dati dei giocatori sono stati eliminati."
L["All Realms"] = "Tutti i Reami"
L["Bag %d Item %d:"] = "Borsa %d Oggetto %d:"
--[[Translation missing --]]
--[[ L["Bag %d:"] = "Bag %d:"--]] 
L["Bags"] = "Borse"
L["Bank"] = "Banca"
L["Bank Item %d:"] = "Oggetto nella Banca %d:"
L["BankItems Bindings"] = "Collegamenti BankItems"
L["BankItems Options"] = "Opzioni di BankItems"
L["BANKITEMS_CAUTION_TEXT"] = "ATTENZIONE: Alcuni elementi non sono stati analizzati/mostrati, su questo rapporto, perché non esistono più nella tua cache di WoW. Un recente aggiornamento di WoW o del suo lanciatore ha provocato una pulizia della cache locale. Accedi con questo personaggio e visita la banca per eseguire una correzione OPPURE sposta il cursore su ogni oggetto in ogni borsa per interrogare il server (questo potrebbe disconnetterti)"
--[[Translation missing --]]
--[[ L["BANKITEMS_CAUTION_TEXT_2"] = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"--]] 
L["Check to show all saved characters, regardless of realm or faction."] = "Seleziona per mostrare tutti i personaggi salvati, indipendentemente dal reame e la fazione."
L["Check to show characters from the opposite faction (includes BankItems tooltips)."] = "Seleziona per mostrare i personaggi della fazione opposta (include tooltip di BankItems)"
L["Contents of:"] = "Contenuti di:"
--[[Translation missing --]]
--[[ L["Delete a Character:"] = "Delete a Character:"--]] 
--[[Translation missing --]]
--[[ L["Delete a Guild:"] = "Delete a Guild:"--]] 
--[[Translation missing --]]
--[[ L["Delete Data for..."] = "Delete Data for..."--]] 
--[[Translation missing --]]
--[[ L["Entry Limit %d"] = "Entry Limit %d"--]] 
L["Equipped"] = "Equipaggiato"
L["Equipped Items"] = "Equipaggiamento indossato"
L["Export BankItems..."] = "Esporta BankItems..."
L["Group similar items"] = "Raggruppa gli stessi articoli"
L["GuildBank"] = "GuildBank"
L["has"] = "ne ha"
--[[Translation missing --]]
--[[ L["Hold down|cffeda55f Alt|r to show %d additional entries"] = "Hold down|cffeda55f Alt|r to show %d additional entries"--]] 
L["Ignore unstackable soulbound items"] = "Ignora oggetti che non possono essere raggruppati"
L["Include the following guild banks:"] = "Includi le seguenti Banche di Gilda:"
L["Items in Mailbox"] = "Oggetti nella Cassetta della Posta"
L["Left-click to open BankItems."] = "<Click Sinistro> per aprire BankItems."
L["Lock main window from being moved"] = "Blocca la finestra principale per non essere spostata"
L["Mailbox data not found. Please visit the mailbox on this character."] = "Dati della Posta non trovati. Per favore, visita una casella postale con questo personaggio."
L["Minimap Button Position %d"] = "Posizione Pulsante Minimappa %d"
L["Minimap Button Radius %d"] = "Raggio Pulsante Minimappa %d"
L["Money (cumulative)"] = "Denaro (cumulativo)"
L["Money:"] = "Denaro:"
L["No Guild Bank Data"] = "Nessun dato della Banca di Gilda"
L["No Guild Bank Tabs"] = "Nessun scomparto della Banca di Gilda"
L["Note - Blizzard frames doesn't like it if your scale isn't 100% when using this option."] = "Nota - i frame della Blizzard non apprezzano, quando utilizzi questa opzione, una proporzione al di sotto del 100%."
L["of"] = "di"
L["OfflineBank"] = "OfflineBank"
L["On the command \"/bi\":"] = "Al comando \"/bi\":"
L["Open auction house bag"] = "Apri la borsa della Asta"
L["Open bank bags"] = "Apri le Borse della Banca"
L["Open BankItems and..."] = "Apri BankItems e..."
L["Open BankItems bags with Blizzard bags"] = "Apri le Borse di BankItems con le borse di Blizzard"
L["Open BankItems with Blizzard windows"] = "Apri BankItems con le finestre di Blizzard"
L["Open currencies bag"] = "Apri la Borsa delle Monete"
L["Open equipped items bag"] = "Apri la Borsa con gli equipaggiamenti indossati"
L["Open inventory bags"] = "Apri le Borse dell'Inventario"
L["Open mail bag"] = "Apri la Borsa della Posta"
L["Open reagent bank"] = "Apri la Banca dei Reagenti"
L["Open void storage bag"] = "Apri la Borsa della Banca Eterea"
L["Options..."] = "Opzioni..."
L["Right-click and drag to move this button."] = "<Click Destro> per spostare e muovere questo pulsante."
L["Scaling %d%%"] = "Proporzione %d%%"
L["Search bank and bank bags"] = "Cerca nella Banca e nelle sue Borse"
L["Search BankItems..."] = "Cerca BankItems..."
L["Search equipped gear"] = "Cerca equipaggiamento indossato"
L["Search for \"%s\" complete."] = "La ricerca per \"%s\" è stata completata."
--[[Translation missing --]]
--[[ L["Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."] = "Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."--]] 
L["Search guild banks"] = "Cerca nelle Banche di Gilda"
L["Search inventory bags"] = "Cerca nelle Borse dei vari Inventari"
L["Search mailbox"] = "Cerca nelle Cassette della Posta"
L["Search these bags..."] = "Cerca queste Borse..."
--[[Translation missing --]]
--[[ L["Show All Characters"] = "Show All Characters"--]] 
L["Show All Realms"] = "Mostra tutti i Reami"
L["Show bag prefix"] = "Mostra prefisso Borsa"
--[[Translation missing --]]
--[[ L["Show character gold in total gold tooltip"] = "Show character gold in total gold tooltip"--]] 
L["Show extra item tooltip information"] = "Mostre informazioni extra nel tooltip"
--[[Translation missing --]]
--[[ L["Show only exact item matches in tooltip counts"] = "Show only exact item matches in tooltip counts"--]] 
L["Show Opposite Faction"] = "Mostra la Fazione Opposta"
L["Show reagent bank contents in a bag"] = "Mostra i contenuti della Banca dei Reagenti in una borsa"
L["Show the minimap button"] = "Mostra il pulsante nella minimappa"
L["Show void storage contents in a bag"] = "Mostra i contenuti della Banca Eterea in una borsa"
--[[Translation missing --]]
--[[ L["Sort Ascending"] = "Sort Ascending"--]] 
--[[Translation missing --]]
--[[ L["Sort data broker gold tooltip in ascending order"] = "Sort data broker gold tooltip in ascending order"--]] 
--[[Translation missing --]]
--[[ L["Tab %d"] = "Tab %d"--]] 
L["Tab %d Item %d:"] = "Etichetta %d Oggetto %d:"
L["Toggle BankItems"] = "Scambia BankItems"
L["Toggle BankItems and all Bags"] = "Scambia BankItems e tutte le Borse"
L["Toggle BankItems and all Bank Bags"] = "Scambia BankItems e tutte le Borse della Banca"
L["Toggle BankItems Guild Bank"] = "Scambia Banca di Gilda BankItems"
L["Total"] = "Totale"
L["Total: %d"] = "Totale: %d"
L["Transparency %d%%"] = "Transparenza %d%%"
L["Type /bi or /bankitems to open BankItems"] = "Digita /bi o /bankitems per aprire BankItems"
L["View bank/inventory/mail contents from anywhere!"] = "Visualizza i contenuti di Banca/Inventario/Posta ovunque!"
L["View Guild Bank contents from anywhere!"] = "Visualizza i contenuti della Banca di Gilda ovunque!"
L["You do not have any guild bank data to display."] = "Non hai nessun dato relativo alla Banca di Gilda da mostrare."
L["You have not seen the contents of \"%s\" before"] = "Non hai mai visto prima il contenuto \"%s\""

