-- BankItems esES/esMX Locale File (Credits: FireAllianceNX)
-- THE CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/projects/bank-items/localization/

if GetLocale() ~= "esES" and GetLocale() ~= "esMX" then return end
local L = BANKITEMS_LOCALIZATION

--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to limit to %d entries"] = "     |cffeda55f Click|r to limit to %d entries"--]] 
--[[Translation missing --]]
--[[ L["     |cffeda55f Click|r to show %d additional entries"] = "     |cffeda55f Click|r to show %d additional entries"--]] 
L["-- /bi all : open BankItems and all bags"] = "-- /bi all :  Abre BankItems y todas las bolsas"
L["-- /bi allbank : open BankItems and all bank bags only"] = "-- /bi allbank : abre BankItems y todas las bolsas del banco del jugador"
L["-- /bi charname : open bank of charname on the same server"] = "-- /bi <nombrejugador> : abrir banco del personaje <nombrejugador> en el mismo reino"
L["-- /bi clear : clear currently selected player's info"] = "-- /bi clear : Borra la informacion del personaje seleccionado"
L["-- /bi clearall : clear all players' info"] = "-- /bi clearall : borra la información de todos los personajes."
L["-- /bi hidebutton : hide the minimap button"] = "-- /bi hidebutton : Oculta el boton del minimapa"
L["-- /bi open charname : open bank of charname on the same server"] = "-- /bi open <nombrejugador> : abrir banco del personaje <nombrejugador> en el mismo reino"
L["-- /bi search itemname : search for items"] = "-- /bi search <nombreobjeto>: Busca objetos"
L["-- /bi showbutton : show the minimap button"] = "-- /bi showbutton : Muestra el boton del minimapa"
L["-- /bigb : open BankItems guild bank"] = "-- /bigb : abre BankItems banco de hermandad"
L["-- /bigb clear : clear currently selected guild's info"] = "-- /bigb clear : Borra la informacion de la hermandad seleccionada"
L["-- /bis itemname : search for items"] = "-- /bis <nombreobjeto>: busca objetos"
--[[Translation missing --]]
--[[ L["%.0fK"] = "%.0fK"--]] 
--[[Translation missing --]]
--[[ L["%.1fK"] = "%.1fK"--]] 
L["%d guild bank(s) selected"] = "%d Banco hermandad seleccionado"
L["%dg %ds %dc"] = "%do %dp %dc"
--[[Translation missing --]]
--[[ L["%s data appears out-of-date."] = "%s data appears out-of-date."--]] 
--[[Translation missing --]]
--[[ L["%s data appears out-of-date. Please visit the %s on this character."] = "%s data appears out-of-date. Please visit the %s on this character."--]] 
L["%s data not found. Please log on this character."] = "%s datos no encontrados. Por favor conéctate con este personaje."
L["%s data not found. Please visit the Auction House on this character."] = "%s datos no encontrados. Por favor visita la casa de subastas con este personaje."
--[[Translation missing --]]
--[[ L["%s data not found. Please visit the Bank on this character."] = "%s data not found. Please visit the Bank on this character."--]] 
L["%s data not found. Please visit the Void Storage on this character."] = "%s datos no encontrados. Por favor visita el desposito de vacio con este personaje."
--[[Translation missing --]]
--[[ L["%s not unlocked on this character."] = "%s not unlocked on this character."--]] 
L["(Not seen before)"] = "( No visto antes)"
L["|cffeda55fAlt-Click|r to toggle BankItems %s"] = "|cffeda55fAlt-Click|r para alternar BankItems %s"
L["|cffeda55fClick|r to toggle BankItems"] = "|cffeda55fClick|r para alternar BankItems"
L["|cffeda55fCtrl-Click|r to toggle BankItems %s"] = "|cffeda55fCtrl-Click|r para alternar BankItems %s"
L["|cffeda55fShift-Click|r to toggle BankItems %s"] = "|cffeda55fShift-Click|r para alternar BankItems %s"
L["<%s>'s guild bank has not purchased any guild bank tabs."] = "<%s> Esta hermandad no ha comprado ninguna pestaña del banco"
L["All players' data have been cleared."] = "Todos los datos de los jugadores han sido borrados."
L["All Realms"] = "Todos los Reinos"
L["Bag %d Item %d:"] = "Bolsa %d  Objeto %d:"
--[[Translation missing --]]
--[[ L["Bag %d:"] = "Bag %d:"--]] 
L["Bags"] = "Bolsas"
L["Bank"] = "Banco"
L["Bank Item %d:"] = "Objeto en Banco %d:"
L["BankItems Bindings"] = "Ligar teclas a BankItems"
L["BankItems Options"] = "BankItems Opciones"
L["BANKITEMS_CAUTION_TEXT"] = "Cuidado: Algunos objetos no han sido registrados en este informe por que no existen en su cache local de Wow todavia. Un reciente parche de WoW o actualizacion del lanzador causo la limpieza del cache local. Accede en este personaje y visita el banco para corregir esto O bien pasa el raton sobre cada objeto en cada una de las bolsas para forzar la respuesta del servidor para cada objeto (esto puede desconectarte) "
--[[Translation missing --]]
--[[ L["BANKITEMS_CAUTION_TEXT_2"] = "CAUTION: Some items were not parsed/displayed in this report because the server did not return their item name and they do not exist in your WoW local cache yet. Please try your search again or log on the following character(s) and visit the bank to correct this:"--]] 
L["Check to show all saved characters, regardless of realm or faction."] = "Señala para mostrar todos los personajes guardados, sin restriccion de Reino o faccion."
L["Check to show characters from the opposite faction (includes BankItems tooltips)."] = "Señala para mostrar los personajes de la Facción contraria ( incluye BI anotaciones)"
L["Contents of:"] = "Contenido de"
--[[Translation missing --]]
--[[ L["Delete a Character:"] = "Delete a Character:"--]] 
--[[Translation missing --]]
--[[ L["Delete a Guild:"] = "Delete a Guild:"--]] 
--[[Translation missing --]]
--[[ L["Delete Data for..."] = "Delete Data for..."--]] 
--[[Translation missing --]]
--[[ L["Entry Limit %d"] = "Entry Limit %d"--]] 
L["Equipped"] = "Equipado"
L["Equipped Items"] = "Objetos Equipados"
L["Export BankItems..."] = "Exportar BankItems..."
L["Group similar items"] = "Agrupa objetos similares"
L["GuildBank"] = "Banco de Hermandad"
L["has"] = "tiene"
--[[Translation missing --]]
--[[ L["Hold down|cffeda55f Alt|r to show %d additional entries"] = "Hold down|cffeda55f Alt|r to show %d additional entries"--]] 
L["Ignore unstackable soulbound items"] = "Ignorar objetos ligados no apilables"
L["Include the following guild banks:"] = "Incluye los siguientes bancos de hermandad:"
L["Items in Mailbox"] = "Objetos en el correo"
L["Left-click to open BankItems."] = "Click izquierdo para abrir BankItems."
L["Lock main window from being moved"] = "Bloquea la ventana principal para que no se mueva"
L["Mailbox data not found. Please visit the mailbox on this character."] = "%s datos no encontrados. Por favor visita un buzón con este personaje."
L["Minimap Button Position %d"] = "Posición del botón del minimapa %d"
L["Minimap Button Radius %d"] = "Radio del boton del minimapa"
L["Money (cumulative)"] = "Dinero (acumulativo)"
L["Money:"] = "Dinero:"
L["No Guild Bank Data"] = "Sin datos de Banco de Hermandad"
L["No Guild Bank Tabs"] = "Sin Pestañas en Banco de Hermandad"
L["Note - Blizzard frames doesn't like it if your scale isn't 100% when using this option."] = "Nota - A la Interface de Blizzard no le gusta si tu escala no es 100% cuando usas esta opción."
L["of"] = "de"
L["OfflineBank"] = "Banco desconectado"
L["On the command \"/bi\":"] = "con el Comando \"/bi\":"
L["Open auction house bag"] = "Abrir bolsa de la casa de subastas"
L["Open bank bags"] = "Abre bolsas del banco"
L["Open BankItems and..."] = "Abrir BankItems y..."
L["Open BankItems bags with Blizzard bags"] = "Abre las bolsas de BankItems con las de Blizzard."
L["Open BankItems with Blizzard windows"] = "Abre BankItems con la ventana de Blizzard"
L["Open currencies bag"] = "Abre bolsa de Monedas"
L["Open equipped items bag"] = "Abre bolsa de objetos equipados"
L["Open inventory bags"] = "Abre Bolsa de Inventario"
L["Open mail bag"] = "Abre bolsa de correo"
L["Open reagent bank"] = "Abrir banco de componentes"
L["Open void storage bag"] = "Abrir bolsa del deposito de vacio"
L["Options..."] = "Opciones..."
L["Right-click and drag to move this button."] = "Click derecho y arrastra para mover este boton."
L["Scaling %d%%"] = "Escala "
L["Search bank and bank bags"] = "Busca banco y bolsas de banco"
L["Search BankItems..."] = "Busca BankItems"
L["Search equipped gear"] = "Busca Equipo Equipado"
L["Search for \"%s\" complete."] = "Busqueda \"%s\"  completa"
--[[Translation missing --]]
--[[ L["Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."] = "Search for \"%s\" exceeded the %d line limit. Please try a more specific search term."--]] 
L["Search guild banks"] = "Busca Banco Hermandad"
L["Search inventory bags"] = "Busca Bolsa Inventario"
L["Search mailbox"] = "Busca Correo"
L["Search these bags..."] = "Busca Estas Bolsas"
--[[Translation missing --]]
--[[ L["Show All Characters"] = "Show All Characters"--]] 
L["Show All Realms"] = "Muestra Todos Los Reinos"
L["Show bag prefix"] = "Muestra el prefijo de Bolsa"
--[[Translation missing --]]
--[[ L["Show character gold in total gold tooltip"] = "Show character gold in total gold tooltip"--]] 
L["Show extra item tooltip information"] = "Muestra Informaciñon extra en la anotación"
--[[Translation missing --]]
--[[ L["Show only exact item matches in tooltip counts"] = "Show only exact item matches in tooltip counts"--]] 
L["Show Opposite Faction"] = "Muestra Faccion Contraria"
L["Show reagent bank contents in a bag"] = "Mostrar contenido del banco de componentes en una bolsa"
L["Show the minimap button"] = "Muestra el boton de minimapa"
L["Show void storage contents in a bag"] = "Mostrar el contenido del depositio de vacio en una bolsa"
--[[Translation missing --]]
--[[ L["Sort Ascending"] = "Sort Ascending"--]] 
--[[Translation missing --]]
--[[ L["Sort data broker gold tooltip in ascending order"] = "Sort data broker gold tooltip in ascending order"--]] 
--[[Translation missing --]]
--[[ L["Tab %d"] = "Tab %d"--]] 
L["Tab %d Item %d:"] = "Pestaña %d Objeto %d:"
L["Toggle BankItems"] = "Intercambia BankItems"
L["Toggle BankItems and all Bags"] = "Alterna BankItems y todas las bolsas"
L["Toggle BankItems and all Bank Bags"] = "Alterna BankItems y todas las bolsas del banco"
L["Toggle BankItems Guild Bank"] = "Intercambia BankItems Banco de Hermandad"
L["Total"] = "Total"
L["Total: %d"] = "Total: %d"
L["Transparency %d%%"] = "Trasparencia %d%%"
L["Type /bi or /bankitems to open BankItems"] = "Escribe /bi o /bankitems para abrir BankItems"
L["View bank/inventory/mail contents from anywhere!"] = "Ver el contenido  Banco/Inventario/Correo desde cualquier parte!"
L["View Guild Bank contents from anywhere!"] = "Ver Banco de Hermandad desde cualquier parte!"
L["You do not have any guild bank data to display."] = "No tienes ningun Banco de Hermandad para Mostrar"
L["You have not seen the contents of \"%s\" before"] = "No has visto los contenidos de la pestaña \"%s\" antes."

